### ISSUE TITLE
Update to Vue2 and Firebase3

### ISSUE THREAD

**Issue by mketiku** [coligo-io/bookmarking-app-electron-vuejs-firebase#2]
Hi @FadyMak, thanks for the tutorial. I am loving Vue.js so far. I have run into a problem using this repo. I cloned it to my machine and run npm install and get error with the dependency for babel, connecting to firebase and using vue2/vue-loader.

Are you still planning to update the tutorial or the repo in any way? I would really appreciate it if you could, if not could you point me in the direction to get the application working?

**Comment by FadyMak** [comment]
Hi @mketiku, I'm glad you're enjoying Vue! I'm sorry, I've been very slow to update the tutorials to the latest versions of Vue, Firebase, etc..

The goal is to update them sometime soon but I don't have a specific time to give unfortunately! I'll do my best to to get them up to date as soon as possible though

**Comment by mketiku** [comment]
No problem I'll check back some other time, thanks again for the tutorials!

**Comment by dmk255** [comment]
Just want to follow up on this thread. I've been following along with the tutorial but it is (expectedly) not working with vue 2.0.x. Are there any planned updates to this?

If not I'll see if I can get it working and submit a PR

**Comment by FadyMak** [comment]
Hi @dmk255! Your PRs are most welcome :) I plan to update all the Vue tutorials on Coligo and I began prioritizing the articles that will be updated and this one is definitely on the list.

**Comment by mketiku** [comment]
Hey dmk255, have you had any luck converting the tutorial to Vue 2.0?

**Comment by jlavelle** [comment]
@mketiku, I have a fork [here](https://github.com/jlavelle/bookmarking-app-electron-vuejs-firebase) updated for Vue 2 and Firebase 3.  To get it working you have to go to your Firebase console, get the web app configuration to add to the store code, and disable auth on the database.  Not PR friendly, Vue events changed quite a bit in 2.0 so I just tacked the component events onto the store to get something working.

**Comment by Guizzoni** [comment]
How's the Vue 2 and Firebase 3 update coming along?
